name: Gerar APK Manual

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main-androidStudio

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Permission
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: APK-TCC
          path: app/build/outputs/apk/debug/*.apk